name: Telco ColorCoder 

on: [push, pull_request]

env:
  DOTNET_VERSION: '8.0.x'

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug]

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Resharper
      uses: glassechidna/resharper-action@master
      with:
        solution: TelCo.ColorCoder.sln
    - name: Run the App
      run: dotnet run --project TelCo.ColorCoder 
